# runtime/version.py
RUNTIME_VERSION = "0.2.0"

EXPORT_VERSION = 1
SNAPSHOT_VERSION = 1
BACKUP_VERSION = 1

# Resource policy limits
MAX_CPU_PERCENT = 80
MAX_MEMORY_MB = 512
RESOURCE_VIOLATION_LIMIT = 3
