"""
Secrets Manager for FunPay Hub.

Manages encryption via Fernet (symmetric, AES-128-CBC with HMAC).
Behaviour:
1. If ENCRYPTION_KEY is set in environment — use it as-is.
2. If ENCRYPTION_KEY is NOT set, try to load from .env file (persistent storage).
3. If neither exists — generate a NEW key, persist it to .env so it survives restarts.

High-level API:
    sm = SecretsManager()
    sm.get_secret("GORGONABOOSTS_API_KEY")  # environ -> encrypted store -> ""
    sm.set_secret("GORGONABOOSTS_API_KEY", "my-key")  # encrypt + persist
"""
import json
import os
import re
import logging
from pathlib import Path
from typing import Optional

from cryptography.fernet import Fernet

logger = logging.getLogger("FunPayHUB.SecretsManager")

# Path for the encrypted secrets store
_SECRETS_STORE_PATH = Path(__file__).resolve().parent.parent / "configs" / "secrets" / "encrypted_secrets.json"


def _project_root() -> Path:
    """Return the project root directory (where .env lives)."""
    import sys
    if getattr(sys, "frozen", False):
        return Path(sys.executable).resolve().parent
    # Walk up from this file's location to find the project root
    return Path(__file__).resolve().parent.parent


def _dotenv_path() -> Path:
    return _project_root() / ".env"


def _load_key_from_dotenv() -> bytes | None:
    """
    Read ENCRYPTION_KEY from .env file (if it exists).
    Returns the key as bytes, or None.
    """
    env_file = _dotenv_path()
    if not env_file.exists():
        return None
    try:
        text = env_file.read_text(encoding="utf-8")
        match = re.search(
            r'^ENCRYPTION_KEY\s*=\s*([^\s#"\']+)',
            text,
            re.MULTILINE,
        )
        if match:
            raw = match.group(1).strip()
            # .env values may or may not be quoted — strip surrounding quotes
            raw = raw.strip("'\"")
            if raw:
                return raw.encode("utf-8")
    except Exception as exc:
        logger.warning("Failed to read ENCRYPTION_KEY from .env: %s", exc)
    return None


def _save_key_to_dotenv(key: bytes) -> None:
    """
    Write (or update) ENCRYPTION_KEY in .env so it persists across restarts.
    """
    env_file = _dotenv_path()
    key_line = f'ENCRYPTION_KEY={key.decode("utf-8")}'

    if not env_file.exists():
        # Create .env with the key and a short comment
        header = (
            "# ENCRYPTION_KEY — auto-generated by security/secrets_manager.py\n"
            "# Do NOT share or commit this file.\n"
        )
        env_file.write_text(
            header + key_line + "\n",
            encoding="utf-8",
        )
        logger.info("Created .env with fresh ENCRYPTION_KEY")
        return

    # Update existing .env — replace or append
    try:
        old_text = env_file.read_text(encoding="utf-8")
        if re.search(r'^ENCRYPTION_KEY\s*=', old_text, re.MULTILINE):
            new_text = re.sub(
                r'^ENCRYPTION_KEY\s*=.*$',
                key_line,
                old_text,
                count=1,
                flags=re.MULTILINE,
            )
        else:
            new_text = old_text.rstrip("\n") + "\n" + key_line + "\n"
        env_file.write_text(new_text, encoding="utf-8")
        logger.info("Updated ENCRYPTION_KEY in .env")
    except Exception as exc:
        logger.warning("Failed to update .env with ENCRYPTION_KEY: %s", exc)


def _resolve_key() -> bytes:
    """
    Resolve the encryption key with the following priority:
    1. ENVIRONMENT variable ENCRYPTION_KEY
    2. .env file (persistent storage)
    3. Generate fresh + persist to .env
    """
    # 1. Environment variable
    env_key = os.environ.get("ENCRYPTION_KEY")
    if env_key:
        logger.info("Using ENCRYPTION_KEY from environment")
        return env_key.encode("utf-8")

    # 2. .env file
    dotenv_key = _load_key_from_dotenv()
    if dotenv_key:
        logger.info("Using ENCRYPTION_KEY from .env file")
        # Also load into os.environ so other code can see it
        os.environ["ENCRYPTION_KEY"] = dotenv_key.decode("utf-8")
        return dotenv_key

    # 3. Generate fresh
    new_key = Fernet.generate_key()
    logger.warning(
        "ENCRYPTION_KEY not found anywhere — generating new key and persisting to .env"
    )
    _save_key_to_dotenv(new_key)
    # Also set in os.environ for this process
    os.environ["ENCRYPTION_KEY"] = new_key.decode("utf-8")
    return new_key


class SecretsManager:
    def __init__(self):
        self.key = _resolve_key()
        self.cipher = Fernet(self.key)

    def encrypt_secret(self, secret: str) -> str:
        """Encrypt a secret value (returns Fernet token string)."""
        return self.cipher.encrypt(secret.encode()).decode()

    def decrypt_secret(self, encrypted: str) -> str:
        """Decrypt an encrypted secret value."""
        return self.cipher.decrypt(encrypted.encode()).decode()

    def get_encryption_key(self) -> str:
        """Get the current encryption key."""
        return self.key

    def get_secret(self, name: str, default: str = "") -> str:
        """
        Retrieve a secret by name.

        Priority:
        1. Environment variable (os.environ[name])
        2. Encrypted secrets store (configs/secrets/encrypted_secrets.json)
        3. default value
        """
        # 1. Environment variable
        env_val = os.environ.get(name)
        if env_val:
            return env_val

        # 2. Encrypted store
        try:
            store = self._load_store()
            encrypted = store.get("secrets", {}).get(name)
            if encrypted:
                return self.decrypt_secret(encrypted)
        except Exception as exc:
            logger.warning("Failed to read secret '%s' from store: %s", name, exc)

        # 3. Default
        return default

    def set_secret(self, name: str, value: str) -> bool:
        """
        Encrypt and persist a secret value.

        The value is encrypted with the current ENCRYPTION_KEY and stored
        in configs/secrets/encrypted_secrets.json.  It does NOT write to .env
        (that file is for env vars, not encrypted blobs).
        """
        try:
            encrypted = self.encrypt_secret(value)
            store = self._load_store()
            store.setdefault("secrets", {})[name] = encrypted
            self._save_store(store)
            logger.info("Secret '%s' encrypted and saved to store", name)
            return True
        except Exception as exc:
            logger.error("Failed to save secret '%s': %s", name, exc)
            return False

    def delete_secret(self, name: str) -> bool:
        """
        Remove a secret from the encrypted store."""
        try:
            store = self._load_store()
            if name in store.get("secrets", {}):
                del store["secrets"][name]
                self._save_store(store)
                logger.info("Secret '%s' removed from store", name)
            return True
        except Exception as exc:
            logger.error("Failed to delete secret '%s': %s", name, exc)
            return False

    # ------------------------------------------------------------------
    # Encrypted store I/O
    # ------------------------------------------------------------------

    def _load_store(self) -> dict:
        try:
            if _SECRETS_STORE_PATH.exists():
                raw = _SECRETS_STORE_PATH.read_text(encoding="utf-8")
                return json.loads(raw) if raw.strip() else {"version": "1.0", "secrets": {}}
        except Exception as exc:
            logger.warning("Failed to load secrets store: %s", exc)
        return {"version": "1.0", "secrets": {}}

    def _save_store(self, store: dict) -> None:
        _SECRETS_STORE_PATH.parent.mkdir(parents=True, exist_ok=True)
        _SECRETS_STORE_PATH.write_text(
            json.dumps(store, ensure_ascii=False, indent=2),
            encoding="utf-8",
        )

    def rotate_key(self) -> str:
        """Rotate the encryption key and re-encrypt all secrets."""
        old_key = self.key
        new_key = Fernet.generate_key()
        self.key = new_key
        self.cipher = Fernet(self.key)
        _save_key_to_dotenv(new_key)

        # Re-encrypt all stored secrets with the new key
        try:
            store = self._load_store()
            secrets = store.get("secrets", {})
            for name, encrypted_value in list(secrets.items()):
                try:
                    decrypted = Fernet(old_key).decrypt(encrypted_value.encode()).decode()
                    secrets[name] = self.encrypt_secret(decrypted)
                except Exception:
                    logger.warning("Could not re-encrypt '%s', removing", name)
                    secrets.pop(name, None)
            self._save_store(store)
        except Exception as exc:
            logger.warning("Failed to re-encrypt secrets: %s", exc)

        logger.info("Encryption key rotated and all secrets re-encrypted")
        return new_key